all: Client_Test Server_Test

Client_Test: Client_Test.cpp
	g++ -o Client_Test -lFeheConnection -std=c++11 Client_Test.cpp

Server_Test: Server_Test.cpp
	g++ -o Server_Test -lFeheConnection -std=c++11 Server_Test.cpp
